
# folder path of dataset, which includes 2 subfolders: cloud/ and ground_truth/
datasets_dir: ../data/RICE_DATASET/RICE2/
train_list: train_list.txt
test_list: test_list.txt
out_dir: results

cuda: True
gpu_ids: [0]

train_size: 0.8
validation_size: 0.2 # 验证集大小是占训练集的半分比
batchsize: 1
validation_batchsize: 1
epoch: 200
n_data: 433
width: 512
height: 512
threads: 4

lr: 0.0004
beta1: 0.5
lamb: 100
minimax: 1

gen_init: 
dis_init: 
in_ch: 3
out_ch: 3

manualSeed: 0
snapshot_interval: 50
